version: "3.7"
services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: db_app
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env_docker

  redis:
    image: redis:7-alpine
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370

  app:
    build:
      context: .
    env_file:
      - .env_docker
    container_name: fastapi_practice
    command: [ "/fastapi_app/docker/app.sh" ]
    ports:
      - "9999:8000"
    depends_on:
      - db
      - redis
    environment:
      PYTHONPATH: /fastapi_app/src

  celery:
    build:
      context: .
    env_file:
      - .env_docker
    container_name: celery_app
    command: [ "/fastapi_app/docker/celery.sh", "celery" ]
    depends_on:
      - redis

  flower:
    build:
      context: .
    env_file:
      - .env_docker
    container_name: flower_app
    command: [ "/fastapi_app/docker/celery.sh", "flower" ]
    depends_on:
      - redis
      - celery
    ports:
      - "8888:5555"

volumes:
  postgres_data: